### ISSUE TITLE
support Windows

### ISSUE THREAD

**Issue by skaji** [perl-actions/install-with-cpm#3]
GitHub Actions made CI in Windows easy.
It's nice perl-actions/install-cpm supports Windows.

**Comment by atoomic** [comment]
sure I'm going to add some tests for it

**Comment by atoomic** [comment]
I've added a sample in the README to use windows and one CI job to confirm it's working
I think it's better to let the user install windows

view: https://github.com/perl-actions/install-with-cpm/runs/596643713?check_suite_focus=true

```yaml
  windows:
    runs-on: windows-latest
    name: "windows"

    steps:
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "##[add-path]C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin"

      - name: perl -V
        run: perl -V

      - uses: actions/checkout@v2
      - name: "install-with-cpm"

        uses: perl-actions/install-with-cpm@v1.2
        with:
          install: |
            abbreviation
            ACH
      # checking that both modules are installed
      - run: perl -Mabbreviation -e1
      - run: perl -MACH -e1
```
