### ISSUE TITLE
configuration

### ISSUE THREAD

**Issue by skaji** [perl-actions/install-with-cpm#4]
I think it is reasonable for install-cpm to have some options:
```
uses: perl-actions/install-cpm@v1.0
with:
  perl: /usr/local/bin/perl
  path: /usr/local/bin/cpm
  version: 0.991
  sudo: false
```

Here
* `perl` Which perl to be used with cpm. If this is specified, rewrite the shebang in cpm.
* `path` The install path of cpm. The default value would be `$Config{installsitescript}/cpm`.
* `version` The version of cpm. Note that you can fetch cpm with a specific version by `https://raw.githubusercontent.com/skaji/cpm/<version>/cpm` url. 
* `sudo` Use sudo when locating cpm.

**Comment by atoomic** [comment]
excellent going to add them in addition to the additional I got
```
with:
   install: 'Module'
   cpanfile: 'cpanfile' # one or more modules
   tests: true | false
   global: true | false # control -g
   args: '--any --extra --args for installation'
```
